name: ESP-IDF Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build firmware (esp32s3)
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.0.1
          target: esp32s3
